# Generated by Django 4.0.4 on 2022-06-26 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_current_song'),
        ('spotify', '0002_votes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Votes',
            new_name='Vote',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='song',
            new_name='song_id',
        ),
    ]
